SCREEN_W, SCREEN_H = 800, 600
GROUND_HEIGHT = SCREEN_H - 62

BG_SCALE = 2.68
PLAYER_SCALE = 2.9
BRICK_SCALE = 2.69
ENEMY_SCALE = 2.5
ENEMY_SPEED = 1
FONT = 'D:\game\pictures\简菱心_0.TTF'
GRAVITY = 1
ANTI_GRAVITY = 0.6  # 反重力